include:
  - project: 'docker/process-webhooks'
    file: '/gitlab/deploy.yml'

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROJECT_TO_BE_DEPLOYED: 'docker/conjugador'

stages:
  - test
  - build
#  - deploy

test:
  image: python:3.11.0-slim-bullseye
  before_script:
    - apt-get update && apt-get install make
    - python -m pip install --upgrade pip
    - pip install uv
    - uv sync

  stage: test
  script:
    - make test

build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
  stage: build
  script:
#    - docker build -f docker/dockerfile --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
#    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
#    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - export REPO_NAME=$CI_REGISTRY_IMAGE/conjugador-elastic
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=docker/elasticsearch/Dockerfile
    - docker build -f $DOCKER_PATH --tag $IMAGE_NAME .
    - docker push $IMAGE_NAME

    - export REPO_NAME=$CI_REGISTRY_IMAGE/conjugador-webserver
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - export DOCKER_PATH=docker/webserver/Dockerfile
    - docker build -f $DOCKER_PATH --tag $IMAGE_NAME .
    - docker push $IMAGE_NAME
    

#deploy:
#  stage: deploy
#  extends:
#    .default-deploy
